vuejs-translations/docs-fr

src/translations/index.md
=> Translations page

.github/contributing/writing-guide.md
Traduction du guide d'écriture
=> translated writing guide

src/about/team.md, src/about/team/TeamMember.vue, src/about/team/TeamPage.vue, src/about/team/members-core.json, src/about/team/members-emeriti.json, src/about/team/members-partner.json
Traduction de la page équipe.
Je n'ai pas traduit les postes occupés car il y en a qui ne sont pas vraiment traduisibles et ils n'étaient pas traduits non plus dans la documentation de Vue 2.
(J'ai également corrigé certains liens vers des projets et des photos de profil qui étaient cassés, il faudra rapporter les modifs sur le repo [vuejs/docs](https://github.com/vuejs/docs) je pense)
=> Translate team page

.vitepress/theme/components/Banner.vue, .vitepress/theme/components/Home.vue, .vitepress/theme/components/NewsLetter.vue, .vitepress/theme/components/ReplLoading.vue, .vitepress/theme/components/VueMasteryModal.vue, .vitepress/theme/components/VueSchoolLink.vue
Traduction et corrections des textes dans les composants du thème.
=> Translate text in theme components

.vitepress/config.ts
Corrections dans le fichier de config VitePress
=> Fix typos in config

src/guide/components/props.md
resolves #27
Cherry picked from https://github.com/vuejs/docs/commit/dbdabb377b34fda3e9abae46a9f0008fc8ebd064
=> fix: Minor grammatical error in props.md (#27)

.vitepress/config.ts, src/tutorial/src/step-2/description.md
resolves #31
Cherry picked from https://github.com/vuejs/docs/commit/e575e79890bb53b5819e8933b441f14b13c43502
=> Adding meta theme-color (#31)

src/guide/components/attrs.md
resolves #34
Cherry picked from https://github.com/vuejs/docs/commit/be5fe376d9b6348114c70d3bb4d2a4b671c59921
=> Minor gramatical error in attrs.md (#34)

src/about/team/TeamList.vue
resolves #44
Cherry picked from https://github.com/vuejs/docs/commit/32515361dbd720065fb631a058ba232e90bbe31c
=> Fix wrong shuffled team members info (#44)

src/about/team/members-partner.json
resolves #69
Cherry picked from https://github.com/vuejs/docs/commit/c991f6d6468157bc46aa15147eef0be80a4aa540
=> fix wrong url (#69)

src/api/component-instance.md, src/api/options-state.md, src/api/reactivity-core.md
resolves #74
Cherry picked from https://github.com/vuejs/docs/commit/93d4aa65ac3870deff7e541730920c9f3baaac96
=> Add a note about `flush: 'sync'`, with links from elsewhere (#74)

src/api/component-instance.md, src/api/options-state.md, src/api/reactivity-core.md, src/guide/best-practices/performance.md
resolves #76
Cherry picked from https://github.com/vuejs/docs/commit/9a6021dbd9cd34b18ec83c4fd813b0fc4ac15635
=> Update the note about Vue Router and lazy loading (#76)

src/api/component-instance.md, src/api/options-state.md, src/api/reactivity-core.md, src/guide/best-practices/performance.md, src/guide/scaling-up/testing.md
resolves #78
Cherry picked from https://github.com/vuejs/docs/commit/ac2010955869de02ed105b25fa4d556ab0ee6862
=> Fix Testing Library example (#78)

src/guide/best-practices/performance.md, src/guide/extras/ways-of-using-vue.md
resolves #91
Cherry picked from https://github.com/vuejs/docs/commit/80005420a92759d5232c62d496c268034b5b926f
=> improve the loading perf section and more details for ssg (#91)

.vitepress/config.ts, .vitepress/jobsMdPlugin.ts, .vitepress/theme/components/VueJobs.vue, .vitepress/theme/index.ts, src/sponsor/index.md
resolves #93
Cherry picked from https://github.com/vuejs/docs/commit/b925d8ac0a17e4ab38f1df90331215667bde3a32
=> Move VueJobs widget to page headings (#93)

src/guide/extras/ways-of-using-vue.md
resolves #95
Cherry picked from https://github.com/vuejs/docs/commit/34b768211f810eb04751e22f0c75c4ceb0e14f09
=> Fix typo (#95)

.vitepress/jobsMdPlugin.ts
resolves #97
Cherry picked from https://github.com/vuejs/docs/commit/74449a840c88ee9488e2337081302a993e14e1f6
=> exclude sponsor page for ad injection (#97)

src/examples/src/crud/App/template.html
resolves #101
Cherry picked from https://github.com/vuejs/docs/commit/3d896c5adf8267d10448f398051ee976fb3920e8
=> Update template.html (#101)

src/guide/typescript/composition-api.md
resolves #105
Cherry picked from https://github.com/vuejs/docs/commit/a63c429102f74917891b5aac919d1c2b471a33a1
=> Update link to Takeover Mode (#105)

src/guide/extras/animation.md, src/guide/typescript/composition-api.md
resolves #107
Cherry picked from https://github.com/vuejs/docs/commit/9cac663ff01b50532c5a77cf8405058ecf954293
=> Adjust an example template in animation.md (#107)

src/guide/extras/animation.md, src/guide/extras/reactivity-in-depth.md, src/guide/typescript/composition-api.md
resolves #109
Cherry picked from https://github.com/vuejs/docs/commit/78d4828482075f1187d0eb71ec4f6fdbecade986
=> Small tweaks to the introduction of reactivity-in-depth.md (#109)

src/guide/essentials/event-handling.md
resolves #111
Cherry picked from https://github.com/vuejs/docs/commit/c94694b1070828fd7455c04437979a8e73a8483a
=> Add missing possessive apostrophes (#111)

.vitepress/config.ts, src/guide/essentials/conditional.md
Translation of page conditional rendering
=> docs(Conditional Rendering)

src/index.md
=> feat: translate home frontmatter

.vitepress/config.ts
resolves #140
Cherry picked from https://github.com/vuejs/docs/commit/3b928f7630eb8039cc316dc8604513bd43cf810c
=> add placeholder of the i18n config for translations (#140)

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
resolves #157
Cherry picked from https://github.com/vuejs/docs/commit/73661d8ee6d486a830130870032ac06ee1ab06c4
=> remove vue toronto banner (#157)

src/guide/built-ins/keep-alive.md, src/guide/essentials/computed.md, src/guide/essentials/conditional.md, src/guide/extras/render-function.md
resolves #179
Cherry picked from https://github.com/vuejs/docs/commit/7826a0167ef1236a3aadf2c24c0587935e853da1
=> Explain attribute inheritance for functional components (#179)

src/about/team/TeamList.vue, src/api/reactivity-utilities.md, src/guide/essentials/watchers.md
resolves #186
Cherry picked from https://github.com/vuejs/docs/commit/381861a14fde1339e8b68ba77cb19533b77869f5
=> Add computed refs to isReadonly (#186)

src/api/ApiIndex.vue, src/api/api.data.ts
resolves #197
Cherry picked from https://github.com/vuejs/docs/commit/11bd76fa9a3e01cea60257af77c23645fcb4008d
=> Fix API index heading text (#197)

.vitepress/theme/components/VueMasteryBanner.vue, src/about/faq.md
resolves #204
Cherry picked from https://github.com/vuejs/docs/commit/07dcd19880f01419b3c84d7e2cbf31b80bba5b9c
=> vue mastery banner mobile fix (#204)

.vitepress/config.ts, src/api/built-in-special-attributes.md, src/api/component-instance.md, src/api/composition-api-setup.md, src/guide/essentials/template-refs.md
=> guide/essentials/template-refs.md 

.vitepress/config.ts, src/guide/essentials/list.md, src/style-guide/index.md
=> style-guide/index.md

.vitepress/config.ts, .vscode/settings.json, src/style-guide/rules-strongly-recommended.md
=> style-guide/rules-strongly-recommended.md

.vitepress/config.ts, src/style-guide/rules-use-with-caution.md
=> style-guide/rules-use-with-caution.md

.vitepress/config.ts, src/style-guide/rules-essential.md
=> style-guide/rules-essential.md

.vitepress/config.ts, src/style-guide/rules-recommended.md
=> style-guide/rules-recommended.md

.vitepress/config.ts, src/guide/best-practices/accessibility.md
Closes #137
Remarques :
- Nouvelle branche avec un historique git propre.
- Remplace https://github.com/vuejs-translations/docs-fr/pull/152
=> accessibilité en FR

.vitepress/config.ts, src/api/application.md, src/api/general.md, src/guide/extras/ways-of-using-vue.md, src/guide/extras/web-components.md
Closes #368 
Remarques:
- Par certain de la traduction de Eager
- `shadowRoot` et `shadow DOM` préservé tel quel car terme technique
=> feat: web components

src/guide/scaling-up/testing.md, src/partners/components/PartnerPage.vue
Quelques typos corrigées dans `testing.md`
=> Fix:testing.md

CONTRIBUTING.md
@edimitchel est-ce qu'il faut faire un fichier du même genre pour le processus de relecture ?
=> Fix relecture.md

src/examples/src/svg/App/template.html
=> fix forgotten translation of template.html in svg example section

src/api/composition-api-lifecycle.md, src/guide/essentials/application.md, src/guide/extras/reactivity-transform.md, src/guide/scaling-up/testing.md, src/guide/typescript/overview.md
Normalement le projet est désormais clean à ce niveau!
J'en ai profité pour corriger deux typos dans `overview.md`.
=> replace APIs with API

src/guide/essentials/application.md
Petite relecture de cette page pour commencer à corriger les exemples ayant été traduits! 👍
=> review essentials/application.md

src/guide/essentials/template-syntax.md
Même chose, suppression des traductions des exemples + review 👍
=> review essentials/template-syntax.md

src/examples/src/hello-world/App/composition.js, src/examples/src/hello-world/description.txt
Closes #222  
Remarques:
- gotta try to push more from now
=> DRAFT: chore translate examples

.vitepress/theme/components/PreferenceSwitch.vue, src/api/built-in-directives.md, src/guide/essentials/template-syntax.md, src/guide/quick-start.md, src/guide/scaling-up/sfc.md, src/sponsor/index.md
=> fix broken links

.vitepress/config.ts
=> add link back to official docs

src/guide/best-practices/accessibility.md, src/guide/essentials/class-and-style.md, src/guide/essentials/event-handling.md, src/guide/essentials/forms.md, src/guide/extras/web-components.md, src/guide/reusability/custom-directives.md, src/guide/scaling-up/tooling.md, src/tutorial/src/step-2/description.md
Pour chaque lien en-Us j'ai bien vérifié que le lien FR existait!
=> replace en-Us links with fr links

.vitepress/config.ts
j'ai refait une passe sur `config.ts`
=> translate config.ts

src/guide/best-practices/accessibility.md
Les exemples de code doivent-ils être retraduits en FR ?
=> review accessibility.md

src/api/composition-api-setup.md
Just a minor correction of the french version of composition-api-setup.md file. `La méthode "increment" serait dès lors disponible dans le composant parent via une référence.` => `La méthode "increment" sera dès lors disponible dans le composant parent via une référence.`
Closes # 
Remarques:
=> Grammarly correction

src/api/sfc-spec.md, src/guide/best-practices/accessibility.md, src/guide/built-ins/transition.md, src/guide/essentials/class-and-style.md, src/guide/reusability/composables.md, src/guide/scaling-up/sfc.md, src/style-guide/rules-strongly-recommended.md
=> fix: comments correction

.vitepress/config.ts, src/examples/src/form-bindings/App/composition.js, src/examples/src/form-bindings/App/options.js, src/examples/src/form-bindings/App/template.html, src/examples/src/form-bindings/description.txt
=> feat: translate example

src/guide/typescript/overview.md
=> guide/typescript/overview.md 

src/guide/essentials/lifecycle.md, src/guide/essentials/list.md, src/guide/essentials/reactivity-fundamentals.md, src/guide/typescript/composition-api.md
=> Translation of reactivity-fundamentals page 

src/examples/src/cells/Cell/template.html, src/guide/extras/demos/SpreadSheetCell.vue
resolves #512
Cherry picked from https://github.com/vuejs/docs/commit/4ba12e46654b50d5a01d72584b1db92ecd8577f0
=> docs: change @vnode-mounted to @vue:mounted (#512)

src/guide/scaling-up/ssr.md
Closes # 
Remarques: This PR is related to [#2445](https://github.com/vuejs/docs/issues/2445).
=> Fixed missing Node.js Streams API links

src/glossary/index.md
Issues:
vuejs-translations#527
English:
https://fr.vuejs.org/glossary/#async-component
Closes # 
Remarques:
=> docs(glossary): translation of async component

.vitepress/config.ts, src/glossary/index.md, src/guide/components/events.md
=> docs(glossary): dynamic component, effect and event

src/glossary/index.md
Issues:https://github.com/vuejs-translations/docs-fr/issues/529 English Version: https://vuejs.org/glossary/#composition-api
Closes # 
Remarques:
=> docs(glossary): translate composition API

src/guide/components/v-model.md
missing translation handling-v-model-modifiers #532 https://github.com/vuejs-translations/docs-fr/issues/532
Closes # 
Remarques:
=> docs(components): translate example intro #532

.vitepress/theme/components/PreferenceSwitch.vue, src/guide/extras/composition-api-faq.md, src/guide/introduction.md, src/guide/reusability/composables.md, src/guide/scaling-up/sfc.md
Alignement de la manière dont on nomme les différentes API.
=> fix: alignement nom d'API

src/glossary/index.md
#543 directive
https://fr.vuejs.org/glossary/#directive
https://github.com/vuejs-translations/docs-fr/issues/543
Closes # 
Remarques:
=> docs(glossary): translate directive #543

src/guide/components/provide-inject.md
http://localhost:5173/guide/components/provide-inject.html#inject Translate missing translation in Composition API inject #546
https://github.com/vuejs-translations/docs-fr/issues/546
Closes # 
Remarques:
=> docs(inject): translate #546

src/guide/essentials/reactivity-fundamentals.md
=> 526 update reactivity fundamentalsmd

src/guide/essentials/reactivity-fundamentals.md
https://github.com/vuejs-translations/docs-fr/issues/523
Closes # 
Remarques:
=> chore(reactivity): update new change #523

.github/contributing/writing-guide.md
https://github.com/vuejs-translations/docs-fr/issues/514
Closes # 
Remarques:
=> docs: update vitepress link #514

src/api/reactivity-core.md
https://github.com/vuejs-translations/docs-fr/issues/553
Closes # 
Remarques:
=> fix(reactivity): remove anchor

src/guide/reusability/plugins.md
Translate the view more title
Closes # 
Remarques:
=> fix(plugin): translate the show more title #564

src/glossary/index.md
https://github.com/vuejs-translations/docs-fr/issues/565
Closes # 
Remarques:
=> docs(glossary): translate VNode #565

src/guide/reusability/composables.md
=> 563 fix missing translation in composable

src/glossary/index.md
https://github.com/vuejs-translations/docs-fr/issues/574
Closes # 
Remarques:
=> docs(glossary): translate render function #574

src/glossary/index.md
https://github.com/vuejs-translations/docs-fr/issues/575
Closes # 
Remarques:
=> docs(glossary): translate the slot #575

src/glossary/index.md
=> 572 reactivity api

.vitepress/config.ts
https://github.com/vuejs-translations/docs-fr/issues/580
Closes # 
Remarques:
=> docs(menu): translate the menu header #580

src/partners/partners.json
resolves #586
Cherry picked from https://github.com/vuejs/docs/commit/61e4f235c95203b4bb9862cce70d836a103d045b
=> fix: update monterail link (#586)

src/glossary/index.md
=> docs(glossary): component

src/guide/introduction.md
Closes : #595 (issue connected to #458)
=> [#595] - Update masculine to feminine

src/glossary/index.md
=> 599 functional component

src/glossary/index.md
=> docs(glossary): translate inject #609

src/glossary/index.md
=> 607 in dom template

src/glossary/index.md
=> 613 lifecycle hooks

src/glossary/index.md
=> 611 provide inject

src/glossary/index.md
=> 520 web component

src/glossary/index.md
https://github.com/vuejs-translations/docs-fr/issues/617
Closes # 
Remarques:
=> docs(glossary): named slot #617

src/guide/scaling-up/tooling.md
https://github.com/vuejs-translations/docs-fr/issues/619
Closes # 
Remarques:
=> docs(tools): translate link title #619

src/guide/scaling-up/routing.md
https://github.com/vuejs-translations/docs-fr/issues/621
Closes # 
Remarques:
Je me dis qu'ici çà doit être routage en se basant sur le terme utilisé plus bas https://fr.vuejs.org/guide/scaling-up/routing.html
=> docs(guide): translate title routing #621

src/guide/scaling-up/testing.md
https://vuejs.org/guide/scaling-up/testing.html#e2e-testing
https://fr.vuejs.org/guide/scaling-up/testing.html#e2e-testing
Closes # 
Remarques:
=> docs(guide): Fix the link to follow english #625

src/partners/partners.json
=> docs(partners): remove jump 24 #615

src/guide/scaling-up/testing.md
=> 623 missing translation in recipes httpsfrvuejsorgguidescaling uptestinghtmle2e testing

src/glossary/index.md
=> from 636 to 638 single file component vdom sfc

src/glossary/index.md
=> 634 reactivity

src/glossary/index.md
=> translate(glossary): options api + plugins

src/glossary/index.md
=> 632 reactive effect

src/glossary/index.md
=> 642 template ref

src/examples/ExampleRepl.vue, src/guide/components/v-model.md
resolves #651
Cherry picked from https://github.com/vuejs/docs/commit/6d12f2c8b8f4170fe8c6dcf58196f339db699527
=> perf: remove `resize` event listener when `unmounted` (#651)

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
resolves #646
Cherry picked from https://github.com/vuejs/docs/commit/eba914e68eacceab35826e4aa8d017c80ad0ab49
=> feat: add vuetoronto23 banner (#646)

src/glossary/index.md
=> 644 side effect

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
=> 665 remove vuetoronto23 banner

src/glossary/index.md
=> 671 scoped slot

src/glossary/index.md
=> 669 scheduler

src/glossary/index.md
=> 673 virtual dom

src/glossary/index.md
=> docs(glossary): delete warning

src/guide/reusability/composables.md
Closes #677
Remarques:
A single space was present in line 226. I took the initiative to remove it as other lines.
=> docs(composable): update restrictions text ##677

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
resolves #691
Cherry picked from https://github.com/vuejs/docs/commit/71ecfd5fb8f1ac82c4d5ee4ef72f4685d119040e
=> Add Vue Toronto banner - schedule 2 (#691)

src/about/team/TeamMember.vue
resolves #720
Cherry picked from https://github.com/vuejs/docs/commit/7b9eb9c043291a11552189cb416ecd5bd7aafc1f
=> imported and changed twitter icon to new logo (#720)

src/guide/scaling-up/testing.md
Closes # 
Remarques:
De manière générale je ne vois pas de grande différence entre les changements effectués en Anglais et celle en Français.
=> 719 docs use usebyrole in example and fix typos

src/guide/essentials/watchers.md
https://github.com/vuejs/docs/commit/c979157fc1536b718410e55d626f510baf76c1c0
Closes # 
Remarques:
=> Chore: Update the watcher examples #717

src/guide/components/registration.md
https://github.com/vuejs/docs/commit/666561eaec82b2e15cd5ad40ccdd9b1eabebca9b
Closes # 
Remarques:
=> Chore: Remove the app constant name #714

src/guide/components/events.md
https://github.com/vuejs/docs/commit/626a4bf6b040f189d48f0f0b2555b1346a5375f0
Closes # 
Remarques:
=> chore: Update the events options #712

src/guide/best-practices/accessibility.md
=> Chore: Repor the consistent colons #715

.vitepress/config.ts
resolves #731
Cherry picked from https://github.com/vuejs/docs/commit/8c16348aaf8c154d3bbcdcd5bba5a372a65d959d
=> chore: temporarily remove vueschool script (#731)

src/style-guide/rules-recommended.md
https://github.com/vuejs/docs/commit/575a6a7c0351edd481289c1a64bc34ce0629d45b
Closes # 
Remarques:
=> chore: update rules-recommended #713

.vitepress/theme/components/SponsorsGroup.vue, .vitepress/theme/components/sponsors.ts, src/api/reactivity-core.md
resolves #743
Cherry picked from https://github.com/vuejs/docs/commit/67f4d3a366baa96ea8edd66f36c21dcd4fdb6de7
=> fix: ref example (#743)

.vitepress/theme/components/SponsorsGroup.vue
resolves #739
Cherry picked from https://github.com/vuejs/docs/commit/07cac45939b8e5fbae5c89039ff1059c3bb7f112
=> fix aside special max height (#739)

src/translations/index.md
resolves #753
Cherry picked from https://github.com/vuejs/docs/commit/70dfbd1c021590e33a0062efa368b64c21561130
=> Add Persian to WIP languages (#753)

src/guide/scaling-up/testing.md
https://github.com/vuejs-translations/docs-fr/issues/764
Closes # 
Remarques:
=> Feat: Remove Peeky test util and update jest #764

package.json, pnpm-lock.yaml, src/examples/ExampleRepl.vue, src/tutorial/TutorialRepl.vue
=> 755 choredeps bump vue vitepress vuerepl and theme

src/style-guide/index.md, src/style-guide/rules-essential.md, src/style-guide/rules-recommended.md, src/style-guide/rules-use-with-caution.md
=> 762 docs add composition api to style guide

.vitepress/theme/components/Home.vue
resolves #780
Cherry picked from https://github.com/vuejs/docs/commit/6f6757656c4f5dc1678454da6da31fe6ab56d8d3
=> style: fix Special Sponsor loading (#780)

src/guide/quick-start.md
https://github.com/vuejs-translations/docs-fr/issues/777
Closes # 
Remarques:
=> Chore: Set the required minimun version of node #777

src/guide/typescript/overview.md
=> Chore: Update the isolatedModules typescript #779

src/guide/best-practices/accessibility.md
https://github.com/vuejs-translations/docs-fr/issues/793
Closes # 
Remarques:
=> Docs: replaces 'Not available' with 'search' #793

src/about/coc.md
https://github.com/vuejs-translations/docs-fr/issues/795
Closes # 
Remarques:
=> Feat: sync with contributor-covenant attribution #795

.vitepress/theme/components/VueMasteryBanner.vue
resolves #805
Cherry picked from https://github.com/vuejs/docs/commit/09d541ae75e0e4eb24e902977547235eacd37e2d
=> fix: change redirection link (#805)

src/guide/components/v-model.md
resolves #847
Cherry picked from https://github.com/vuejs/docs/commit/5cbf0bff51a01880c07909d6972d5f1cdf874bd9
=> remove unnecessary import from example (#847)

src/guide/components/events.md
https://github.com/vuejs-translations/docs-fr/issues/845
Closes # 
Remarques:
=> Fix: Remove event as props #845

src/guide/essentials/template-refs.md
https://github.com/vuejs-translations/docs-fr/issues/846
Closes # 
Remarques:
=> Chore: Correct template ref grammar #846

src/error-reference/index.md
=> feat(3.4): src/error-reference/index.md

src/api/sfc-script-setup.md
=> feat(3.4): src/api/sfc-script-setup.md

src/translations/index.md
resolves #889
Cherry picked from https://github.com/vuejs/docs/commit/98628dd0c6391f805b1be0955a26b89ccc009ac4
=> feat: Add Czech to WIP languages (#889)

src/guide/essentials/template-syntax.md
=> Fix(template-syntax.md): add closing tag #879

src/about/team/members-core.json
=> Chore: Update core member 

src/guide/extras/ways-of-using-vue.md
=> Feat: Update the way how to use vuejs

.vitepress/config.ts, .vitepress/theme/styles/index.css
resolves #896
Cherry picked from https://github.com/vuejs/docs/commit/95d5e5d21d2743def23ef6cc5a5a045e362bbc4f
=> chore: move shikiji workaround (#896)

vercel.json
=> chore: add vercel config for translations #888

src/translations/index.md
resolves #898
Cherry picked from https://github.com/vuejs/docs/commit/c2e0d8e8a36c7f99bbb297268b6c451001a2a51d
=> feat: Add Arabic to WIP languages (#898)

src/guide/extras/render-function.md
Integrate the slots scoped inside the render function
Closes # 
Remarques:
=> Feat: Integrate the scoped slots #900

src/guide/essentials/watchers.md
=> 907 add more details for watcher flush timing

src/guide/essentials/event-handling.md
Closes # 
Remarques:
L'objectif de la issue était d'éviter le scrolling horizontal j'ai en plus mis à jour le commentaire en bas dans le deuxième commit parce que malgré le changement demandé le scrolling horizontal était présent en français.
=> 912 style update event handlingmd avoid horizontal scrolling

src/guide/built-ins/transition-demos/NestedTransitions.vue
resolves #919
Cherry picked from https://github.com/vuejs/docs/commit/64d58ad9a14b302b292b669a033328e330f68b13
=> fix: transition nested example (#919)

src/guide/components/slots.md
https://github.com/vuejs-translations/docs-fr/issues/918
Closes # 
Remarques:
=> Chore: Update slots.md link to Dynamic Argument #918

src/api/sfc-script-setup.md, src/guide/components/v-model.md
=> 924 feat added warnings about v model

src/guide/scaling-up/tooling.md
=> Feat: Update the create vue box #927

src/tutorial/src/step-2/description.md
https://github.com/vuejs-translations/docs-fr/issues/933
Closes # 
Remarques:
=> Docs: fix grammar typo of step 2 #933

src/tutorial/src/step-2/description.md
=> Docs(#934): improve sentence clarity in description.md

src/guide/essentials/reactivity-fundamentals.md
Related to [vuejs/docs@6096ffb](https://github.com/vuejs/docs/pull/2396/commits/6096ffbbaa0bc213864cb2939b61acc285ca4d18#diff-10d1e152d4720391d3e7f68135351884386b7007ecb67e43f266d39f5abfbbafR432)
Remarques:
=> docs: fix translation typo of limitations-of-reactive

src/guide/built-ins/transition.md
resolves #956
Cherry picked from https://github.com/vuejs/docs/commit/e72e53ec7541dbea6c7c2c33312aeb46800f16b9
=> docs: add missing comments to the Options API in the transition page (#956)

src/guide/introduction.md
=> Fix typo error in introduction.md

src/api/compile-time-flags.md
resolves #962
Cherry picked from https://github.com/vuejs/docs/commit/21d4c17faad43a1b294c37063812ab595e66f759
=> Fix "Hydration" typo (#962)

.vitepress/config.ts, src/ecosystem/newsletters.md
resolves #972
Cherry picked from https://github.com/vuejs/docs/commit/90c792983b2c5106ac9216e9a43568cea06e9830
=> remove inactive newsletter (#972)

.vitepress/theme/components/NewsLetter.vue, src/about/community-guide.md
=> 971 use direct discord invite link

src/ecosystem/themes/themes.json
resolves #980
Cherry picked from https://github.com/vuejs/docs/commit/6db6990bd7064fc225de87fdbde648fc94d3c0c9
=> Added Wrappixel Templates (#980)

.gitignore, .idea/.gitignore, .idea/aws.xml, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/docs.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, .vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts, src/ecosystem/themes/themes.json
resolves #983
Cherry picked from https://github.com/vuejs/docs/commit/0910c205e60d1d929a910a15f2501a7308f2f818
=> add vueconf.us banner (#983)

src/guide/best-practices/production-deployment.md, src/guide/extras/composition-api-faq.md
=> 987 docs internal link to compile time flags

src/ecosystem/themes/themes.json
=> Docs: Update themes links

src/guide/reusability/custom-directives.md
=> Docs: Fix typo replace prevNode by prevVnode

.vitepress/config.ts, src/translations/index.md
resolves #1004
Cherry picked from https://github.com/vuejs/docs/commit/702c75a122d6b05ea5219780a5c37e06ef783284
=> Add translation link to fa.vuejs.org (#1004)

src/about/team/Member.ts, src/about/team/TeamMember.vue, src/about/team/TeamPage.vue, src/about/team/members-core.json
=> 1008 docs add kevin deng as core team member

package.json, pnpm-lock.yaml
=> Package: update and set major version vitepress #1006

src/guide/quick-start.md
=> Chore: Update set the version of node to 18.3

src/guide/built-ins/transition.md
https://github.com/vuejs-translations/docs-fr/issues/1002
Closes # 
Remarques:
=> Chore: Change the punctuation #1002

src/guide/quick-start.md
https://github.com/vuejs-translations/docs-fr/issues/993
Closes # 
Remarques:
=> Fix: Syntax highlight #993

src/api/composition-api-dependency-injection.md
https://github.com/vuejs-translations/docs-fr/issues/1001
Closes # 
Remarques:
=> Chore: Change position of see also #1001

src/about/community-guide.md
=> Fix: update link "to show and tell" forum

src/ecosystem/themes/themes.json
resolves #988
Cherry picked from https://github.com/vuejs/docs/commit/f560789e679b652687eeaab46c6276ac6789d32e
=> Added CodedThemes Items (#988)

src/guide/essentials/class-and-style.md
resolves #1020
Cherry picked from https://github.com/vuejs/docs/commit/d01c5b3b6e117a68fd2d82fb2689590df272ea0f
=> Use the correct class variable based on the context (#1020)

.vitepress/config.ts, src/translations/index.md
resolves #1024
Cherry picked from https://github.com/vuejs/docs/commit/e77511d966f350191978450fadd83c59558a0fac
=> feat: czech translation (#1024)

.vitepress/config.ts, .vitepress/theme/index.ts
resolves #1028
Cherry picked from https://github.com/vuejs/docs/commit/66316a0f97d5068f2d9b50ba8cf3b8240309b7e8
=> re-enable vueconf us banner (#1028)

src/guide/introduction.md
https://github.com/vuejs-translations/docs-fr/issues/1041
Closes # 
Remarques:
=> Chore: Update the introduction what is vue #1041

src/guide/components/slots.md
https://github.com/vuejs-translations/docs-fr/issues/1038
Closes # 
Remarques:
=> Feat: Integrate the conditional slots #1038

src/api/sfc-css-features.md
https://github.com/vuejs-translations/docs-fr/issues/1032
Closes # 
Remarques:
=> Chore: Modify link in sfc css features #1032

.vitepress/config.ts, .vitepress/theme/index.ts, src/translations/index.md
resolves #1030
Cherry picked from https://github.com/vuejs/docs/commit/d77e5a1fd0eef251cfa8baa5db1dbc77f2182526
=> Add translation link to ru.vuejs.org (#1030)

src/translations/index.md
https://github.com/vuejs-translations/docs-fr/issues/1030
Closes # 
Remarques:
=> Feat: Integrate the russian language link #1030

src/guide/essentials/component-basics.md
https://github.com/vuejs-translations/docs-fr/issues/1019
Closes # 
Remarques:
=> Chore: Set explicitty link on v-bind #1019

src/guide/quick-start.md, src/guide/scaling-up/tooling.md, src/guide/typescript/overview.md
https://github.com/vuejs-translations/docs-fr/issues/1018
Closes # 
Remarques:
=> Chore: "VSCode" to "VS Code"  #1018

src/examples/utils.ts
resolves #1050
Cherry picked from https://github.com/vuejs/docs/commit/480e12d00d4d6c7c61c90c2877e68f7a292ca819
=> fix: don't trigger onHashChange if path is not the same (#1050)

src/api/built-in-components.md, src/guide/built-ins/suspense.md
=> 1058 fix add missing anchors on suspense

.vitepress/theme/index.ts
resolves #1072
Cherry picked from https://github.com/vuejs/docs/commit/7da76f683954052ba858c174af387497c8f3e5f3
=> disable banner (#1072)

LICENSE
resolves #1079
Cherry picked from https://github.com/vuejs/docs/commit/8cf681562260f8624ef062512485fbc86870dec5
=> update license to CC-BY-4.0 and explicitly exclude images (#1079)

.vitepress/config.ts, src/about/privacy.md
=> 1078 add privacy policy

src/guide/components/props.md
=> 1074 document nullable types

src/ecosystem/themes/themes.json
https://github.com/vuejs-translations/docs-fr/issues/1076
Closes # 
Remarques:
=> Feat: Update themes.json #1076

src/guide/best-practices/accessibility.md
https://github.com/vuejs-translations/docs-fr/issues/1081
Closes # 
Remarques:
=> Style: Set chrom in capitalize #1081

src/examples/src/form-bindings/App/template.html
https://github.com/vuejs-translations/docs-fr/issues/1084
Closes # 
Remarques:
=> Fix: Use <p> iniside example #1084

src/api/sfc-script-setup.md
https://github.com/vuejs-translations/docs-fr/issues/1086
Closes # 
Remarques:
=> Docs: link to suspense #1086

src/api/built-in-components.md, src/guide/built-ins/suspense.md
=> 1091 style remove line breaks in sentences

src/guide/reusability/custom-directives.md
https://github.com/vuejs-translations/docs-fr/issues/1129
Closes # 
Remarques:
=> Feat: Add warning to custom-directives #1129

src/about/privacy.md
https://github.com/vuejs-translations/docs-fr/issues/1133
Closes # 
Remarques:
=> Chore: Update the privacy #1133

src/guide/components/slots.md
Update the slots with default value
Closes # 
Remarques:
=> Chore: Update the slot #1126

src/guide/best-practices/accessibility.md
https://github.com/vuejs-translations/docs-fr/issues/1124
Closes # 
Remarques:
=> Chore: Remove unused comment #1124

src/guide/components/v-model.md
https://github.com/vuejs-translations/docs-fr/issues/1123
Closes # 
Remarques:
=> Docs: Add the docs for v-model #1123

.vitepress/headerMdPlugin.ts
resolves #1144
Cherry picked from https://github.com/vuejs/docs/commit/35e8da8b3811615e3a46770cf4466186ac9ff400
=> fix: broken header plugin (#1144)

.vitepress/headerMdPlugin.ts, src/guide/quick-start.md
resolves #1147
Cherry picked from https://github.com/vuejs/docs/commit/678753fed7aa6922ac105da8a06d356bffbdd91f
=> docs: update /guide/quick-start page (#1147)

.vitepress/theme/components/VueMasteryBanner.vue
https://github.com/vuejs-translations/docs-fr/issues/1149
Closes # 
Remarques:
=> Docs: Update the Vuemastery banner link

.vitepress/theme/styles/inline-demo.css, src/api/sfc-spec.md
resolves #1163
Cherry picked from https://github.com/vuejs/docs/commit/3de891cd0c225b21698503e35f1203f598b970c4
=> style: fix play button alignment (#1163)

.vitepress/headerMdPlugin.ts, package.json, pnpm-lock.yaml
=> Revert: Remove the core #1171

README.md
https://github.com/vuejs-translations/docs-fr/issues/1165
Closes # 
Remarques:
=> Chore: Update node version in readme

src/guide/components/slots.md, src/guide/scaling-up/tooling.md
=> Fix: Update the codesanbox link

.vitepress/config.ts, .vitepress/headerMdPlugin.ts, netlify.toml, package.json, pnpm-lock.yaml
https://github.com/vuejs-translations/docs-fr/issues/1166
Closes # 
Remarques:
=> Chore: bump deps #1166

src/guide/scaling-up/testing.md
=> 1151 docs correct browser support sentences for playwright and cypress

src/guide/built-ins/transition.md, src/guide/reusability/custom-directives.md
https://github.com/vuejs-translations/docs-fr/issues/1155
Closes # 
Remarques:
=> Revert: Remove the csstriggers.com

.npmrc
resolves #1183
Cherry picked from https://github.com/vuejs/docs/commit/e276daba15586ca2f993661cc0d7fe9ce84954d7
=> chore: add .npmrc (#1183)

src/guide/scaling-up/testing.md
https://github.com/vuejs-translations/docs-fr/issues/1150
Closes # 
Remarques:
=> Fix: Remove the breaking link of playwright #1150

src/translations/index.md
https://github.com/vuejs-translations/docs-fr/issues/1187
Closes # 
Remarques:
=> Feat(language): Add spanish is inprogress #1187

package.json, pnpm-lock.yaml
=> Chore: Update the vue-theme package

.vitepress/theme/index.ts
=> Revert: Remove Vuemastery banner #1200

src/guide/extras/composition-api-faq.md
=> Feat: Add not about react compiler #1197

.vitepress/config.ts, package.json, pnpm-lock.yaml
=> Package: Update the dependencies

src/guide/reusability/custom-directives.md
=> Chore: Update custom directive

src/guide/components/v-model.md
=> Fix: Set right v-model value

src/guide/components/v-model.md
=> Chore: Update v-model example #1214

.gitignore, .vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
=> Revert: Remove vueconf.us banner #1209

.vitepress/theme/components/Home.vue, .vitepress/theme/components/SecurityUpdateBtn.vue, .vitepress/theme/index.ts
https://github.com/vuejs-translations/docs-fr/issues/1229
Closes # 
Remarques:
=> Feat: Add the redirect to herodevs site for vue 2 #1229

src/api/render-function.md
resolves #1238
Cherry picked from https://github.com/vuejs/docs/commit/9eaf513ea69b69280a83fd0bc608b80dc4f198ec
=> docs(withModifiers): change type of withModifiers param (#1238)

.vitepress/theme/components/Home.vue
fix https://github.com/vuejs-translations/docs-fr/issues/1242
Sync from commit https://github.com/vuejs/docs/commit/8a4f62706df7b63de0e9f11e8a50b2c1f4bf1aff
=> Fix: incorrect style of the security button

.vitepress/theme/components/Home.vue, .vitepress/theme/components/SecurityUpdateBtn.vue
=> Fix: Ser different background color for dark mode #1244

src/guide/scaling-up/tooling.md
=> Revert: Remove the components studio tools #1237

src/api/sfc-script-setup.md, src/guide/typescript/composition-api.md
=> Feat: Add infor for wrapping reference #1236

.vitepress/theme/components/SecurityUpdateBtn.vue
=> Fix: Set scoped style in security update #1234

src/ecosystem/themes/themes.json
=> 1256 fix themes

src/about/team/members-partner.json
resolves #1253
Cherry picked from https://github.com/vuejs/docs/commit/473305594ac0a8ce774ba9ac3952cc820cbf18c8
=> chore: update team member (#1253)

src/api/sfc-script-setup.md, src/examples/src/fetching-data/App/composition.js, src/examples/src/fetching-data/App/options.js, src/examples/src/fetching-data/App/template.html
resolves #1261
Cherry picked from https://github.com/vuejs/docs/commit/327acb65fa9537e78c4e5d677fcfda121935a8f8
=> fix: render error for fetching-data example (#1261)

.vitepress/theme/components/SponsorsAside.vue
resolves #1275
Cherry picked from https://github.com/vuejs/docs/commit/4d5b2e2f000586785dea7f33a9f7ec7e371a4200
=> chore: correct viteconf CTA utm (#1275)

.vitepress/config.ts, package.json
https://github.com/vuejs-translations/docs-fr/issues/1272
Closes # 
Remarques:
=> Feat: Generate sitemap #1272

.vitepress/theme/styles/style-guide.css
resolves #1283
Cherry picked from https://github.com/vuejs/docs/commit/a66c91698fe1e9314c86ed1729a06d0166c2d485
=> fix: summary add cursor pointer (#1283)

src/guide/quick-start.md, src/guide/scaling-up/tooling.md
=> Chore(started): Update the create vue yarn command

src/guide/scaling-up/testing.md
=> Style(testing): Layout of testing

src/about/team/members-core.json
resolves #1301
Cherry picked from https://github.com/vuejs/docs/commit/059bdf25f42d3ab3368c3a2e43cc8b503af8ddaa
=> Update Yiling's personal information (#1301)

src/guide/essentials/list.md
Use values not keys
Closes # 
Remarques:
=> Fix(v-for): Correct mistake in loop of list #1290

src/api/options-misc.md
https://github.com/vuejs-translations/docs-fr/issues/1296
Closes # 
Remarques:
=> Feat (#1296): Add link how to use inheritattrs

src/about/team/members-emeriti.json
https://github.com/vuejs/docs/commit/44fc18fcf00851f7c2f0b91f544db79784cf4d7c
Closes # 
Remarques:
=> Feat(member): Update defcc latest information #1298

src/guide/best-practices/accessibility.md
https://github.com/vuejs-translations/docs-fr/issues/1343
Closes # 
Remarques:
=> Revert(accessibility): Remove tips in landmarks #1343

src/guide/essentials/forms.md
https://github.com/vuejs-translations/docs-fr/issues/1341
Closes # 
Remarques:
=> Feat(v-model): Clarify unexpected behavior #1341

src/guide/extras/render-function.md
https://github.com/vuejs-translations/docs-fr/issues/1328
Closes # 
Remarques:
=> Fix(render-function): Replace Vnode by VNode #1328

src/api/reactivity-core.md
https://github.com/vuejs-translations/docs-fr/issues/1332
Closes # 
Remarques:
=> Revert(reactivity): Remove the side effects #1332

src/guide/reusability/custom-directives.md
https://github.com/vuejs-translations/docs-fr/issues/1342
Closes # 
Remarques:
=> Fix(custom-directive): Set the directive v-highlight #1342

src/api/application.md
=> 1351 srcapiapplicationmd

src/guide/typescript/composition-api.md
=> 1364 srcguidetypescriptcomposition apimd typing template refs + typing component template refs

src/api/built-in-components.md
=> Docs(api): Update built in component #1358

src/api/reactivity-core.md
=> Docs(reactivity): Add onWatcherCleanup #1360

src/guide/built-ins/suspense.md
=> Chore(suspense): Add supported version #1374

src/guide/typescript/options-api.md, src/guide/typescript/overview.md
=> Fix(link): broken links to dts-test files #1371

src/guide/essentials/template-refs.md
resolves #1385
Cherry picked from https://github.com/vuejs/docs/commit/622e7e5cad19d5f3e9c16816b0ad3ce5ef44aaca
=> docs: remove unnecessary line break (#1385)

src/guide/extras/web-components.md
=> Docs(web-components): Add App Level Config #1398

src/guide/essentials/computed.md
=> 1380 featguidecomputed add previous to computed

src/guide/scaling-up/ssr.md
=> Docs(ssr):  Add  Suppressing Hydration Mismatches #1395

src/guide/essentials/watchers.md
=> 1400 srcguideessentialswatchersmd side effect cleanup

src/guide/components/props.md
=> 1405 srcguidecomponentspropsmd reactive props destructure

src/guide/essentials/template-refs.md
=> 1403 srcguideessentialstemplate refsmd accessing the refs

src/guide/essentials/template-refs.md
resolves #1419
Cherry picked from https://github.com/vuejs/docs/commit/96b9b7c3c3d1f20d609a94642fcabb3eba2df306
=> docs: improve clarity on using refs (#1419)

src/guide/essentials/template-refs.md
=> Fix(template-refs): Fix typo #1427

src/api/composition-api-helpers.md
=> Fix(composition-api-helpers): Set indentation #1425

src/guide/essentials/event-handling.md
=> Fix(event-handling): Set breaking link  #1422

src/guide/essentials/template-refs.md
=> Fix(template-refs): Set right required version #1421

src/guide/essentials/template-syntax.md
=> Chore(template): Replace / by or #1418

src/tutorial/tutorial.data.ts
resolves #1439
Cherry picked from https://github.com/vuejs/docs/commit/cf84ce10597785e6dfa2f2fb6db5d6a0b4810b32
=> fix: Tutorial Syntax Highlight (#1439)

src/about/team/members-core.json
resolves #1444
Cherry picked from https://github.com/vuejs/docs/commit/929aff014b0595dda64f31361e8b37b5d6eb750c
=> Update Natalia's role (#1444)

src/api/sfc-css-features.md
=> Feat(sfc-css-features): Add useCssModule example #1442

src/api/application.md
=> Fix(application): Update the useful link #1437

src/guide/built-ins/transition-group.md
=> Feat(transition-group): Add custom transition group #1438

.vitepress/theme/components/SponsorsGroup.vue
=> Feat(sponsor): Add the special sponsoring #1453

src/about/team/members-core.json, src/about/team/members-emeriti.json
=> Feat(members): Update the emeriti #1460

.vitepress/theme/components/Home.vue, .vitepress/theme/components/SponsorsGroup.vue, src/sponsor/index.md
=> Feat(sponsor): Add special sponsor vacancy hanling #1451

.vitepress/theme/components/PageHero.vue, src/developers/components/DeveloperHero.vue, src/developers/partnerConfig.js, src/partners/components/PartnerHero.vue
=> Feat(partners): Improve the page #1459

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
=> Revert: Remove VueToronto banner #1466

src/guide/essentials/event-handling.md
=> Feat(event-handling): Explanation mouse button #1468

src/examples/src/fetching-data/App/composition.js, src/examples/src/fetching-data/App/options.js, src/examples/src/fetching-data/App/template.html, src/examples/src/fetching-data/description.txt
=> Fix(example): Repo and branch names for fetching #1469

src/about/faq.md
=> Fix(faq): Target ES2016+ on Vue 3.x #1471

src/guide/extras/web-components.md
=> Feat(web-component): Improved the docs on type definitions #1474

src/guide/reusability/custom-directives.md
=> Chore(custom-directive): Update the example content #1475

.vitepress/theme/components/VueMasteryBanner.vue, .vitepress/theme/index.ts, src/public/vuemastery/background-bubbles-vuemastery.svg
=> Feat(promo): Add vuemastery banner #1478

src/guide/essentials/computed.md, src/guide/typescript/composition-api.md
resolves #1492
Cherry picked from https://github.com/vuejs/docs/commit/5936eef341f8c0c62b36d80ad2007b36c10602ee
=> docs(computed): remove semicolons (#1492)

src/guide/components/v-model.md
=> Style(v-model): Set the example more readable #1488

.vitepress/theme/components/SponsorsGroup.vue
resolves #1496
Cherry picked from https://github.com/vuejs/docs/commit/d0a13f7c2d345c9c50bb8bd113e7f7c1105bf9b1
=> update special sponsorship link in sidebar (#1496)

src/guide/extras/web-components.md
=> Fix(web-component): Add missing anchor #1494

src/guide/components/slots.md
=> Fix(slots): Clarify slot precense phrasing #1507

.vitepress/config.ts
=> Build(config): Change the lifecycle hook position #1508

src/guide/essentials/conditional.md, src/guide/essentials/list.md, src/style-guide/index.md, src/style-guide/rules-essential.md, src/style-guide/rules-recommended.md, src/style-guide/rules-strongly-recommended.md, src/style-guide/rules-use-with-caution.md
=> 1504 hide all style guide links and add outdated warnings on style guide p

src/api/application.md
=> Fix(application): Set the component name in PascalCase

.vitepress/theme/components/Banner.vue
=> Style(banner): Update style #1552

src/translations/index.md
=> Feat(lang): Add Deutsh language link #1551

src/api/custom-renderer.md
=> Chore(custom-renderer): Update source code #1536

src/guide/best-practices/performance.md
=> Fix(performance): Update the interaction link

src/api/options-state.md
=> Fix(options-state): Update validator desc #1524

.vitepress/config.ts, .vitepress/theme/components/Home.vue, .vitepress/theme/components/SponsorsGroup.vue, .vitepress/theme/components/sponsors.ts
=> Feat(theme): Update sponsors page #1562

src/guide/best-practices/accessibility.md
=> Chore(accessibility): Update the way of focus #1559

src/partners/partners.json
resolves #1575
Cherry picked from https://github.com/vuejs/docs/commit/f3e9cfb41c21e3c78d1a6ef2a7da2b187b79b755
=> update monterail url (#1575)

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
=> Feat(banner): Add 2025 vueconf banner #1583

src/guide/extras/web-components.md
=> Style(web-component): Remove list styles #1611

src/api/sfc-script-setup.md
=> Feat(sfc-setup): add vue-generic #1609

src/guide/extras/ways-of-using-vue.md
=> Chore: Add Wails as possibility to create vue desktop

src/guide/essentials/list.md
=> Some grammar corrections.md

src/guide/essentials/template-syntax.md
=> Feat(template): Improve the same-name-shorthand

src/about/faq.md
=> Feat: Update FAQ

src/guide/reusability/plugins.md
=> Docs(plugin): Improve explanation provide/inject

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/components/ScrimbaLink.vue, .vitepress/theme/index.ts, src/guide/components/v-model.md, src/guide/essentials/component-basics.md, src/guide/essentials/template-syntax.md, src/guide/quick-start.md, src/guide/typescript/composition-api.md
=> 1640 add scrimba links and remove vue-banner

src/guide/essentials/computed.md
=> Fix(computed): Add correct position

src/ecosystem/themes/themes.json
=> Fix(themes): Fix incorrect URL

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/index.ts
=> Feat: Show vue conf banner

src/guide/extras/ways-of-using-vue.md
=> Feat(petite-vue): Update using

src/guide/reusability/custom-directives.md, src/guide/typescript/composition-api.md
=> Docs(directives): Add using global custom directives

.vitepress/config.ts
=> Revert(link): Remove dead link

.vitepress/config.ts, .vitepress/theme/components/NewsLetter.vue, src/about/community-guide.md, src/about/faq.md, src/about/team/TeamMember.vue, src/about/team/members-partner.json, src/guide/scaling-up/testing.md, src/sponsor/index.md
=> Fix(link): Replace twitter.com by x.com
